name: Build and Publish

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
    branches: "*"
  release:
    types:
      - created

jobs:
  BuildNugetPackage:
    name: Build Nuget Package
    uses: ./.github/workflows/build-nuget-package.yml
    with:
      configuration: Release

  PipelineTests:
    name: Pipeline Tests
    needs: [BuildNugetPackage]
    uses: ./.github/workflows/execute-test.yml
    with:
      configuration: Release
      project_path: ./tests/PipelineTests/src

  UnitTests:
    name: Unit Tests
    needs: [BuildNugetPackage]
    uses: ./.github/workflows/execute-test.yml
    with:
      configuration: Release
      project_path: ./tests/UnitTests

  PublishToGithub:
    name: Publish to Github
    needs: [PipelineTests,UnitTests ]
    uses: ./.github/workflows/publish-to-github.yml
    with:
      package_path: ./src/bin/Release/L0gg3r.Base.*.nupkg


