name: Build and Publish

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
    branches: "*"
  release:
    types:
      - created

jobs:
  BuildNugetPackage:
    name: Build Nuget Package
    uses: ./.github/workflows/build-nuget-package.yml
    with:
      dotnet-version: 7.0.x
      configuration: Release

  PipelineTests:
    name: Pipeline Tests
    needs: [BuildNugetPackage]
    uses: ./.github/workflows/execute-test.yml
    with:
      dotnet-version: 7.0.x
      configuration: Release
      project-path: ./tests/${{ github.job}}/src

  UnitTests:
    name: Unit Tests
    needs: [BuildNugetPackage]
    uses: ./.github/workflows/execute-test.yml
    with:
      dotnet-version: 7.0.x
      configuration: Release
      project-path: ./tests/${{ github.job}}

  PublishToGithub:
    name: Publish to Github
    needs: [PipelineTests,UnitTests ]
    uses: ./.github/workflows/publish-to-github.yml
    with:
      package-path: ./src/bin/Release/L0gg3r.Base.$(basename *.nupkg).nupkg


