name: Build and Publish

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
    branches: "*"
  release:
    types:
      - created

jobs:
  BuildNugetPackage:
    uses: ./.github/workflows/build-nuget-package.yml
    with:
      configuration: Release

  PipelineTests:
    needs: [BuildNugetPackage]
    uses: ./.github/workflows/execute-test.yml
    with:
      configuration: Release
      project_path: ./tests/PipelineTests/src

  UnitTests:
    needs: [BuildNugetPackage]
    uses: ./.github/workflows/execute-test.yml
    with:
      configuration: Release
      project_path: ./tests/UnitTests

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: [Build, Tests]
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: nuget-package
  #     - name: "Add NuGet Source"
  #       run: dotnet nuget add source "https://nuget.pkg.github.com/WolfBublitz/index.json" --username WolfBublitz --password ${GITHUB_TOKEN} --store-password-in-clear-text --name github
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Publish to GitHub
  #       run: dotnet nuget push ./src/bin/Release/*.nupkg -s github


