name: Build and Publish

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
    branches: "*"
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
            6.0.x
            7.0.x
            8.0.x
      - name: "Add NuGet Source"
        run: dotnet nuget add source "https://nuget.pkg.github.com/WolfBublitz/index.json" --username WolfBublitz --password ${GITHUB_TOKEN} --store-password-in-clear-text --name github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Publish to GitHub
        run: dotnet nuget push src/bin/Release/*.nupkg -s https://nuget.pkg.github.com/WolfBublitz/index.json -k ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')


